INSERT INTO items (name, type, market_hash_name)
VALUES
('Sealed Dead Hand Terminal', 'CASE', 'Sealed Dead Hand Terminal'),
('Sealed Genesis Terminal', 'CASE', 'Sealed Genesis Terminal'),
('Fever Case', 'CASE', 'Fever Case'),
('Gallery Case', 'CASE', 'Gallery Case'),
('Kilowatt Case', 'CASE', 'Kilowatt Case'),
('Revolution Case', 'CASE', 'Revolution Case'),
('Recoil Case', 'CASE', 'Recoil Case'),
('Dreams & Nightmares Case', 'CASE', 'Dreams & Nightmares Case'),
('Operation Riptide Case', 'CASE', 'Operation Riptide Case'),
('Snakebite Case', 'CASE', 'Snakebite Case'),
('Operation Broken Fang Case', 'CASE', 'Operation Broken Fang Case'),
('Fracture Case', 'CASE', 'Fracture Case'),
('Prisma 2 Case', 'CASE', 'Prisma 2 Case'),
('Shattered Web Case', 'CASE', 'Shattered Web Case'),
('CS20 Case', 'CASE', 'CS20 Case'),
('Prisma Case', 'CASE', 'Prisma Case'),
('Danger Zone Case', 'CASE', 'Danger Zone Case'),
('Horizon Case', 'CASE', 'Horizon Case'),
('Clutch Case', 'CASE', 'Clutch Case'),
('Operation Hydra Case', 'CASE', 'Operation Hydra Case'),
('Spectrum 2 Case', 'CASE', 'Spectrum 2 Case'),
('Spectrum Case', 'CASE', 'Spectrum Case'),
('Gamma 2 Case', 'CASE', 'Gamma 2 Case'),
('Gamma Case', 'CASE', 'Gamma Case'),
('Glove Case', 'CASE', 'Glove Case'),
('Revolver Case', 'CASE', 'Revolver Case'),
('Shadow Case', 'CASE', 'Shadow Case'),
('Falchion Case', 'CASE', 'Falchion Case'),
('Chroma 3 Case', 'CASE', 'Chroma 3 Case'),
('Chroma 2 Case', 'CASE', 'Chroma 2 Case'),
('Chroma Case', 'CASE', 'Chroma Case'),
('Operation Wildfire Case', 'CASE', 'Operation Wildfire Case'),
('Operation Vanguard Weapon Case', 'CASE', 'Operation Vanguard Weapon Case'),
('Operation Breakout Weapon Case', 'CASE', 'Operation Breakout Weapon Case'),
('Operation Phoenix Weapon Case', 'CASE', 'Operation Phoenix Weapon Case'),
('Operation Bravo Case', 'CASE', 'Operation Bravo Case'),
('Huntsman Weapon Case', 'CASE', 'Huntsman Weapon Case'),
('Winter Offensive Weapon Case', 'CASE', 'Winter Offensive Weapon Case'),
('CS:GO Weapon Case 3', 'CASE', 'CS:GO Weapon Case 3'),
('CS:GO Weapon Case 2', 'CASE', 'CS:GO Weapon Case 2'),
('CS:GO Weapon Case', 'CASE', 'CS:GO Weapon Case'),
('eSports 2013 Winter Case', 'CASE', 'eSports 2013 Winter Case'),
('eSports 2013 Case', 'CASE', 'eSports 2013 Case');
GO